import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Sala from 'App/Models/Sala'

export default class extends BaseSeeder {
  public async run () {
    await Sala.createMany([
      {nome: "LAB01", capacidade: 30, tipo: "P"},
      {nome: "LAB02", capacidade: 30, tipo: "P"},
      {nome: "AA01", capacidade: 30, tipo: "P"},
      {nome: "AA02", capacidade: 30, tipo: "P"},
      {nome: "AA03", capacidade: 30, tipo: "P"},
      {nome: "AA04", capacidade: 30, tipo: "P"},
      {nome: "AA05", capacidade: 30, tipo: "P"},
      {nome: "AA06", capacidade: 30, tipo: "P"},
      {nome: "AA07", capacidade: 30, tipo: "P"},
      {nome: "AA08", capacidade: 30, tipo: "P"},
      {nome: "AA09", capacidade: 30, tipo: "P"},
      {nome: "AA10", capacidade: 30, tipo: "P"},
      {nome: "AA11", capacidade: 30, tipo: "P"},
      {nome: "AA12", capacidade: 30, tipo: "P"},
      {nome: "AA13", capacidade: 30, tipo: "P"},
      {nome: "AA14", capacidade: 30, tipo: "P"},
      {nome: "AA15", capacidade: 30, tipo: "P"},
      {nome: "AB01", capacidade: 30, tipo: "P"},
      {nome: "AB02", capacidade: 30, tipo: "P"},
      {nome: "AB03", capacidade: 30, tipo: "P"},
      {nome: "AB04", capacidade: 30, tipo: "P"},
      {nome: "AB05", capacidade: 30, tipo: "P"},
      {nome: "AB06", capacidade: 30, tipo: "P"},
      {nome: "AB07", capacidade: 30, tipo: "P"},
      {nome: "AB08", capacidade: 30, tipo: "P"},
      {nome: "AB09", capacidade: 30, tipo: "P"},
      {nome: "AB10", capacidade: 30, tipo: "P"},
      {nome: "AB11", capacidade: 30, tipo: "P"},
      {nome: "AB12", capacidade: 30, tipo: "P"},
      {nome: "AB13", capacidade: 30, tipo: "P"},
      {nome: "AB14", capacidade: 30, tipo: "P"},
      {nome: "AB15", capacidade: 30, tipo: "P"},
      {nome: "BC01", capacidade: 30, tipo: "P"},
      {nome: "BC02", capacidade: 30, tipo: "P"},
      {nome: "BC03", capacidade: 30, tipo: "P"},
      {nome: "BC04", capacidade: 30, tipo: "P"},
      {nome: "BC05", capacidade: 30, tipo: "P"},
      {nome: "BC06", capacidade: 30, tipo: "P"},
      {nome: "BC07", capacidade: 30, tipo: "P"},
      {nome: "BC08", capacidade: 30, tipo: "P"},
      {nome: "BC09", capacidade: 30, tipo: "P"},
      {nome: "BC10", capacidade: 30, tipo: "P"},
      {nome: "BC11", capacidade: 30, tipo: "P"},
      {nome: "BC12", capacidade: 30, tipo: "P"},
      {nome: "BC13", capacidade: 30, tipo: "P"},
      {nome: "BC14", capacidade: 30, tipo: "P"},
      {nome: "BC15", capacidade: 30, tipo: "P"},
    ])
  }
}
